## Lab 06


## Powertoys - tools to get the caption of an image

### Understanding Kernals/window/filter

In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

kernel = np.ones((3,3), dtype=int)  # array with ones(1's), K size, type
print(kernel)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


### 1) Image Filtering using 2D convolution.

In [2]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

# Load the image here
img = cv2.imread("D:/SLIIT Y4 S1/IUP/Labs/Lab 6/My/saltandpepper1.png",1)

kernel = np.ones((5,5), np.float32)/25
dst = cv2.filter2D(img, -1, kernel)

result = np.hstack((img,dst))
cv2.imshow('result', result)

cv2.waitKey(0)

[ WARN:0@2.763] global loadsave.cpp:241 findDecoder imread_('D:/SLIIT Y4 S1/IUP/Labs/Lab 6/My/saltandpepper1.png'): can't open/read file: check file path/integrity


error: OpenCV(4.10.0) /Users/runner/work/opencv-python/opencv-python/opencv/modules/imgproc/src/filter.dispatch.cpp:1528: error: (-215:Assertion failed) !_src.empty() in function 'filter2D'


### 2) Image Averaging using Box Filter - Blur

In [17]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

# Load the image here
img = cv2.imread("D:/SLIIT Y4 S1/IUP/Labs/Lab 6/My/saltandpepper1.png",1)

blur = cv2.blur(img,(5,5))

result = np.hstack((img,blur))
cv2.imshow('result', result)

cv2.waitKey(0)

-1

### 2) Image Averaging using Box Filter - Box filter

In [18]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

# Load the image here
# img = cv2.imread("D:/SLIIT Y4 S1/IUP/Labs/Lab 6/My/saltandpepper1.png",1)
img = cv2.imread("D:/SLIIT Y4 S1/IUP/Labs/Lab 6/My/saltandpepper2.png",1)

box = cv2.boxFilter(img,-1, (5,5))

result = np.hstack((img,box))
cv2.imshow('result', result)

cv2.waitKey(0)

-1

### 3) Median Filtering and Gaussian Filtering.

In [34]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

# Load the image here
# img = cv2.imread("D:/SLIIT Y4 S1/IUP/Labs/Lab 6/My/saltandpepper1.png",1)
img = cv2.imread("D:/SLIIT Y4 S1/IUP/Labs/Lab 6/My/saltandpepper2.png",1)

median = cv2.medianBlur(img,5) # 5 -> jernel size

result = np.hstack((img,median))
cv2.imshow('result', result)

cv2.waitKey(0)

-1

### 3) Median Filtering and Gaussian Filtering - blur.

In [38]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

# Load the image here
# img = cv2.imread("D:/SLIIT Y4 S1/IUP/Labs/Lab 6/My/saltandpepper1.png",1)
img = cv2.imread("D:/SLIIT Y4 S1/IUP/Labs/Lab 6/My/gaussian Noise.png",1)

gaussian = cv2.GaussianBlur(img,(11,11),0) #src, ksize, standard devitaion sigmaX

result = np.hstack((img,gaussian))
cv2.imshow('result', result)

cv2.waitKey(0)

-1

### 4) Application of image blurring. - Home work

In [44]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

img3 = cv2.imread("D:/SLIIT Y4 S1/IUP/Labs/Lab 6/My/hubble.png",0)

# Create sutom Kernal of size 15x15 amd apply to the input image
kernel = np.ones((15, 15), np.float32) / 225

dst = cv2.filter2D(img3, -1, kernel)

# Apply threasholding operator to highlight the largest object
_, thresh = cv2.threshold(dst, 127, 255, cv2.THRESH_BINARY)

result = np.hstack((img3, dst, thresh))
cv2.imshow('result', result)

cv2.waitKey(0)

-1